@echo off
echo Starting ML API (Port 5001)...
start "ML API" cmd /k "call .venv\Scripts\activate.bat & python ml_api.py"

echo Starting Middle Server (Port 3000)...
start "Middle Server" cmd /k "node server.js"

echo Starting Main Backend (Port 5000)...
start "Main Backend" cmd /k "cd Backend & node server.js"

echo Starting Frontend Server (Port 8080)...
start "Frontend Server" cmd /k "npx serve Frontend -p 8080"

echo Waiting for servers to start...
timeout /t 5

echo Opening Browser...
start http://localhost:8080
